spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
 
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**

#配置 zuul 开启重试，并配置 ribbon 重试参数
#需要开启重试，默认不开启

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

#降低 hystrix 超时时间，以便测试降级
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

#zuul + hystrix 数据监控
#暴露 hystrix.stream 监控端点
#zuul 已经包含 actuator 依赖
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
